(() => {
  const D=window.USHER_DATA,U=window.USHER,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pmap=Object.fromEntries(D.parties.map(p=>[p.id,p]));
  const fmt=n=>Number(n||0).toLocaleString('en-GB');
  let seatFilter='',councilFilter='';
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
  function partyOptions(selected){return D.parties.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${p.name}</option>`).join('')}
  function declaredSeatTotals(s){const out=Object.fromEntries(D.parties.map(p=>[p.id,0]));Object.values(s.seatResults).forEach(r=>out[r.party]++);return out}
  function declaredCouncilTotals(s){const out=Object.fromEntries(D.parties.map(p=>[p.id,0]));Object.values(s.councilResults).forEach(r=>out[r.party]++);return out}
  function resizePreview(){const frame=$('#previewFrame');if(!frame)return;const iframe=frame.querySelector('iframe');const scale=frame.clientWidth/1920;iframe.style.transform=`scale(${scale})`;frame.style.height=`${1080*scale}px`;}
  window.addEventListener('resize',resizePreview);setTimeout(resizePreview,200);
  function renderSummary(s){const seatCount=Object.keys(s.seatResults).length,councilCount=Object.keys(s.councilResults).length;$('#summaryGrid').innerHTML=`<div class="summary-card"><small>Declared seats</small><strong>${seatCount} / 650</strong></div><div class="summary-card"><small>Majority line</small><strong>326</strong></div><div class="summary-card"><small>Exit poll countdown</small><strong id="controlCountdown" class="red">--:--:--</strong></div><div class="summary-card"><small>Councils declared</small><strong>${councilCount} / 128</strong></div><div class="summary-card"><small>Live presentation</small><strong class="green">${s.currentSlide.toUpperCase()}</strong></div>`;}
  function pollEditorHTML(s){return `<div>${D.parties.map(p=>`<div class="poll-edit-row"><div class="party-label"><span class="party-square" style="background:${p.color}"></span>${p.name}</div><input class="input pollSeats" data-party="${p.id}" type="number" min="0" max="650" value="${s.exitPoll[p.id]||0}"><input class="input pollChange" data-party="${p.id}" type="number" value="${s.exitPollChanges[p.id]||0}"></div>`).join('')}</div><div style="display:flex;gap:8px;margin-top:10px"><button class="btn primary applyPoll">Apply Exit Poll</button><button class="btn danger revealPoll">Push Exit Poll Live</button></div>`}
  function bindPoll(root){root.querySelector('.applyPoll')?.addEventListener('click',()=>{const poll={},changes={};root.querySelectorAll('.pollSeats').forEach(i=>poll[i.dataset.party]=Number(i.value));root.querySelectorAll('.pollChange').forEach(i=>changes[i.dataset.party]=Number(i.value));const total=Object.values(poll).reduce((a,b)=>a+b,0);if(total!==650){toast(`Exit poll totals ${total}, not 650`);return}U.set({exitPoll:poll,exitPollChanges:changes});toast('Exit poll updated')});root.querySelector('.revealPoll')?.addEventListener('click',()=>{U.set({exitPollVisible:true,currentSlide:'exitpoll'});toast('Exit poll pushed live')})}
  function seatFormHTML(s,compact=false){const seat=D.constituencies.find(x=>x.id===s.selectedSeat)||D.constituencies[0];const r=s.seatResults[seat.id];return `<div class="field"><label>Constituency</label><select class="seatSelect">${D.constituencies.map(x=>`<option value="${x.id}" ${x.id===seat.id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>Previous winner</label><select disabled>${partyOptions(seat.previous)}</select></div><div class="field"><label>Prediction</label><select disabled>${partyOptions(seat.prediction)}</select></div></div><div class="form-row"><div class="field"><label>${r?'Declared winner':'Winner'}</label><select class="seatWinner">${partyOptions(r?.party||seat.prediction)}</select></div><div class="field"><label>Majority</label><input class="input seatMajority" type="number" min="0" value="${r?.majority||Math.max(250,Math.round((seat.likelihood-48)*420))}"></div></div><div class="field"><label>Model likelihood</label><input class="input" value="${seat.likelihood}%" disabled></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn danger declareSeat">Declare Result</button><button class="btn primary showSeat">Push Seat Focus</button>${r?'<button class="btn soft undeclareSeat">Undo declaration</button>':''}</div>`}
  function bindSeatForm(root){root.querySelector('.seatSelect')?.addEventListener('change',e=>U.set({selectedSeat:e.target.value}));root.querySelector('.showSeat')?.addEventListener('click',()=>U.set({currentSlide:'seat',mode:'general'}));root.querySelector('.declareSeat')?.addEventListener('click',()=>{const seatId=root.querySelector('.seatSelect').value,party=root.querySelector('.seatWinner').value,majority=Number(root.querySelector('.seatMajority').value)||0;U.update(st=>{st.selectedSeat=seatId;st.seatResults[seatId]={party,majority,time:new Date().toISOString()};st.currentSlide='seat';st.mode='general';});toast('Seat declared')});root.querySelector('.undeclareSeat')?.addEventListener('click',()=>{const seatId=root.querySelector('.seatSelect').value;U.update(st=>{delete st.seatResults[seatId]});toast('Declaration removed')})}
  function councilFormHTML(s){const c=D.councils.find(x=>x.id===s.selectedCouncil)||D.councils[0];const r=s.councilResults[c.id];return `<div class="field"><label>Council</label><select class="councilSelect">${D.councils.map(x=>`<option value="${x.id}" ${x.id===c.id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label>Previous control</label><select disabled>${partyOptions(c.previous)}</select></div><div class="field"><label>Projection</label><select disabled>${partyOptions(c.prediction)}</select></div></div><div class="form-row"><div class="field"><label>Declared control</label><select class="councilWinner">${partyOptions(r?.party||c.prediction)}</select></div><div class="field"><label>Councillor +/-</label><input class="input councilChange" type="number" value="${r?.change||0}"></div></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn danger declareCouncil">Declare Council</button><button class="btn primary showCouncil">Push Council Focus</button>${r?'<button class="btn soft undeclareCouncil">Undo</button>':''}</div>`}
  function bindCouncilForm(root){root.querySelector('.councilSelect')?.addEventListener('change',e=>U.set({selectedCouncil:e.target.value}));root.querySelector('.showCouncil')?.addEventListener('click',()=>U.set({currentSlide:'council',mode:'council'}));root.querySelector('.declareCouncil')?.addEventListener('click',()=>{const id=root.querySelector('.councilSelect').value,party=root.querySelector('.councilWinner').value,change=Number(root.querySelector('.councilChange').value)||0;U.update(st=>{st.selectedCouncil=id;st.councilResults[id]={party,change,time:new Date().toISOString()};st.currentSlide='council';st.mode='council'});toast('Council declared')});root.querySelector('.undeclareCouncil')?.addEventListener('click',()=>{const id=root.querySelector('.councilSelect').value;U.update(st=>{delete st.councilResults[id]});toast('Council declaration removed')})}
  const slides=[['opening','Opening Logo'],['countdown','Exit Poll Countdown'],['exitpoll','Exit Poll'],['national','National Map'],['seat','Constituency Focus'],['council','Council Focus'],['history','History Chart'],['results','Results Board'],['winner','Winner Call'],['break','Break Screen']];
  function managerHTML(s){return `<div class="manager-list">${slides.map(([id,label],i)=>`<div class="manager-row ${s.currentSlide===id?'active':''}"><span>${i+1}</span><strong>${label}</strong><button class="btn showSlide" data-id="${id}">${s.currentSlide===id?'LIVE':'Take'}</button></div>`).join('')}</div>`}
  function bindManager(root){root.querySelectorAll('.showSlide').forEach(b=>b.addEventListener('click',()=>U.set({currentSlide:b.dataset.id}))) }
  function tickerHTML(s){return `<div class="ticker-list">${s.ticker.map((t,i)=>`<div class="ticker-edit-row"><input class="input tickerTime" data-i="${i}" value="${t.time}"><input class="input tickerText" data-i="${i}" value="${t.text}"><button class="btn tickerDelete" data-i="${i}">×</button></div>`).join('')}</div><button class="btn primary tickerSave" style="margin-top:10px">Save Ticker</button>`}
  function bindTicker(root){root.querySelector('.tickerSave')?.addEventListener('click',()=>{const list=[];root.querySelectorAll('.tickerText').forEach((el,i)=>{const idx=Number(el.dataset.i),time=root.querySelector(`.tickerTime[data-i="${idx}"]`).value,text=el.value.trim();if(text)list.push({time,text,party:'oth'})});U.set({ticker:list});toast('Ticker saved')});root.querySelectorAll('.tickerDelete').forEach(b=>b.addEventListener('click',()=>U.update(st=>st.ticker.splice(Number(b.dataset.i),1))))}
  function addTicker(){U.update(st=>st.ticker.push({time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),text:'New live update',party:'oth'}))}
  function renderTables(s){const q=seatFilter.toLowerCase();const seats=D.constituencies.filter(x=>!q||x.name.toLowerCase().includes(q)||x.region.toLowerCase().includes(q)).slice(0,650);$('#seatTable').innerHTML=seats.map(x=>{const r=s.seatResults[x.id];return `<tr data-id="${x.id}" style="cursor:pointer"><td><strong>${x.name}</strong></td><td>${x.region}</td><td>${pmap[x.previous].short}</td><td>${pmap[x.prediction].short}</td><td>${r?`<span class="status-pill live">${pmap[r.party].short} · declared</span>`:'<span class="status-pill">Awaiting</span>'}</td></tr>`}).join('');$('#seatTable').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>U.set({selectedSeat:tr.dataset.id}));const cq=councilFilter.toLowerCase();const councils=D.councils.filter(x=>!cq||x.name.toLowerCase().includes(cq)||x.region.toLowerCase().includes(cq));$('#councilTable').innerHTML=councils.map(x=>{const r=s.councilResults[x.id];return `<tr data-id="${x.id}" style="cursor:pointer"><td><strong>${x.name}</strong></td><td>${x.region}</td><td>${pmap[x.previous].short}</td><td>${pmap[x.prediction].short}</td><td>${r?`<span class="status-pill live">${pmap[r.party].short} · declared</span>`:'<span class="status-pill">Awaiting</span>'}</td></tr>`}).join('');$('#councilTable').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>U.set({selectedCouncil:tr.dataset.id}));}
  function renderExtras(s){$('#presentationExtras').innerHTML=`<div class="field"><label>Winner call party</label><select id="winnerSelect">${partyOptions(s.winnerParty||'lab')}</select></div><button id="pushWinner" class="btn danger">Push Winner Call</button><hr style="border:0;border-top:1px solid #e3e9ef;margin:18px 0"><div class="field"><label>History chart party</label><select id="historySelect">${partyOptions(s.historyParty||'lab')}</select></div><button id="pushHistory" class="btn primary">Push History Chart</button>`;$('#pushWinner').onclick=()=>U.set({winnerParty:$('#winnerSelect').value,currentSlide:'winner'});$('#pushHistory').onclick=()=>U.set({historyParty:$('#historySelect').value,currentSlide:'history'});}
  function renderCountdown(s){const local=new Date(s.exitPollTime);const pad=n=>String(n).padStart(2,'0');const val=`${local.getFullYear()}-${pad(local.getMonth()+1)}-${pad(local.getDate())}T${pad(local.getHours())}:${pad(local.getMinutes())}`;$('#countdownControl').innerHTML=`<div class="field"><label>Exit poll date & time</label><input id="exitPollTime" class="input" type="datetime-local" value="${val}"></div><button id="saveCountdown" class="btn primary">Save Countdown</button> <button data-slide="countdown" class="btn showSlideNow">Push Countdown</button> <button id="revealExit" class="btn danger">Reveal Exit Poll Now</button>`;$('#saveCountdown').onclick=()=>{U.set({exitPollTime:new Date($('#exitPollTime').value).toISOString()});toast('Countdown saved')};$('#revealExit').onclick=()=>U.set({exitPollVisible:true,currentSlide:'exitpoll'});$('#countdownControl').querySelector('.showSlideNow').onclick=()=>U.set({currentSlide:'countdown'});}
  function renderHistoryControl(s){$('#historyControl').innerHTML=`<div class="field"><label>Party</label><select id="historyPartyCtl">${partyOptions(s.historyParty||'lab')}</select></div><p class="muted">The presentation uses stylised historical demonstration data for the selected party.</p><button id="historyTake" class="btn primary">Take History Chart Live</button>`;$('#historyTake').onclick=()=>U.set({historyParty:$('#historyPartyCtl').value,currentSlide:'history'});}
  function renderSystemClock(){const el=$('#controlCountdown');if(!el)return;let ms=new Date(U.getState().exitPollTime)-new Date();if(ms<0)ms=0;const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);el.textContent=[h,m,s].map(v=>String(v).padStart(2,'0')).join(':')}
  setInterval(renderSystemClock,500);
  U.subscribe(s=>{
    renderSummary(s);setTimeout(resizePreview,50);
    $('#dashboardPoll').innerHTML=pollEditorHTML(s);bindPoll($('#dashboardPoll'));$('#exitPollFull').innerHTML=pollEditorHTML(s);bindPoll($('#exitPollFull'));
    $('#dashboardSeat').innerHTML=seatFormHTML(s,true);bindSeatForm($('#dashboardSeat'));$('#generalSeatForm').innerHTML=seatFormHTML(s);bindSeatForm($('#generalSeatForm'));
    $('#dashboardCouncil').innerHTML=councilFormHTML(s);bindCouncilForm($('#dashboardCouncil'));$('#councilForm').innerHTML=councilFormHTML(s);bindCouncilForm($('#councilForm'));
    $('#tickerDash').innerHTML=tickerHTML(s);bindTicker($('#tickerDash'));$('#tickerFull').innerHTML=tickerHTML(s);bindTicker($('#tickerFull'));
    $('#managerDash').innerHTML=managerHTML(s);bindManager($('#managerDash'));$('#managerFull').innerHTML=managerHTML(s);bindManager($('#managerFull'));
    renderTables(s);renderExtras(s);renderCountdown(s);renderHistoryControl(s);renderSystemClock();
  });
  $$('.nav-btn').forEach(b=>b.addEventListener('click',()=>{$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-pane').forEach(x=>x.classList.remove('active'));$(`#tab-${b.dataset.tab}`).classList.add('active');setTimeout(resizePreview,30)}));
  $$('[data-slide]').forEach(b=>b.addEventListener('click',()=>U.set({currentSlide:b.dataset.slide})));
  $('#seatSearch').addEventListener('input',e=>{seatFilter=e.target.value;renderTables(U.getState())});$('#councilSearch').addEventListener('input',e=>{councilFilter=e.target.value;renderTables(U.getState())});
  $('#randomSeat').onclick=()=>U.set({selectedSeat:D.constituencies[Math.floor(Math.random()*D.constituencies.length)].id});$('#randomCouncil').onclick=()=>U.set({selectedCouncil:D.councils[Math.floor(Math.random()*D.councils.length)].id});
  $('#addTickerDash').onclick=addTicker;$('#addTickerFull').onclick=addTicker;$('#previewBtn').onclick=()=>window.open('index.html','usher-preview');$('#openPresentation').onclick=()=>window.open('index.html','usher-live');$('#goLiveBtn').onclick=()=>window.open('index.html','usher-live');$('#saveBtn').onclick=()=>{U.save();toast('Saved')};$('#resetBtn').onclick=()=>{if(confirm('Reset presentation slide and selections?'))U.set({currentSlide:'opening',selectedSeat:D.constituencies[0].id,selectedCouncil:D.councils[0].id})};$('#hardReset').onclick=()=>{if(confirm('Reset ALL results, exit poll settings and ticker data?')){U.reset();toast('All data reset')}};
})();
